"""add user detail

Revision ID: 701d618a6e00
Revises: 609f01bcc0b9
Create Date: 2020-03-12 18:15:45.236420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701d618a6e00'
down_revision = '609f01bcc0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'location')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'create_time')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
